.travis.yml

This PR
Related to #6.
:information_desk_person: Noticed that `composer.lock` is not up to date in [`feature/inflector-config`](https://github.com/tomphp/config-service-provider/tree/feature/inflector-config)!

Enhancement: Validate composer on Travis

---

.travis.yml

Fix: Remove --dev flag when installing, it's the default

---

tests/ConfigServiceProviderTest.php

Fix: Do not declare property dynamically

---

tests/ConfigServiceProviderTest.php

Fix: Add missing letter in test method name

---

tests/ConfigServiceProviderTest.php
tests/FileLocatorTest.php
tests/JSONFileReaderTest.php
tests/PHPFileReaderTest.php
tests/TestFileCreator.php

Fix: Delete test files in tearDown()

---

src/ConfigServiceProvider.php
tests/ConfigServiceProviderTest.php

Fix Allow to read from JSON files when using ConfigServiceProvider::fromFiles()

---

src/FileLocator.php
tests/FileLocatorTest.php

This PR
:information_desk_person: This is very useful (and, admittedly, influenced by [ZF2](https://github.com/zendframework/zend-modulemanager/blob/master/src/Listener/ConfigListener.php#L375-L377)) when you want to use more advanced patterns, say, load global configuration files first, then allow others to override.

Enhancement: Allow to glob with braces

---

.travis.yml

Fix: Cache dependencies between builds

---

src/ConfigServiceProvider.php
tests/ConfigServiceProviderTest.php

This PR
🙎 Related to https://github.com/thephpleague/container/issues/106.

Fix: Make sure that shared configuration values are raw values

---

tests/DIConfigServiceProviderTest.php

Fix: Remove unused local variable

---

src/ConfigServiceProvider.php
src/DIConfigServiceProvider.php

Fix: Add arguments to docblocks

---

src/Exception/EntryDoesNotExistException.php

Fix: Add missing $ to docblock

---

phpunit.xml

Fix: Specify configuration schema and update configuration

---

tests/acceptance/DoesNotSupportInflectors.php
tests/unit/ApplicationConfigTest.php
tests/unit/ConfiguratorTest.php
tests/unit/ContainerAdapterFactoryTest.php
tests/unit/FileReader/JSONFileReaderTest.php
tests/unit/FileReader/PHPFileReaderTest.php
tests/unit/FileReader/ReaderFactoryTest.php

Fix: Use expectException() instead of deprecated setExpectedException()

---

README.md
src/Configurator.php
tests/acceptance/AbstractContainerAdapterTest.php
tests/unit/ConfiguratorTest.php

`Configurator::apply()->configFromFiles('single-file-name.php')->to($container);` has been bothering me. This PR adds a new function for reading a single file.

Add configFromFile()

---

README.md

Fix: References to config-service-provider in README.md

---

.php_cs

This PR
💁 This makes it easier to add new fixers, as it is easier to find items in a list when it is sorted. For this, of course, I used https://plugins.jetbrains.com/plugin/5919?pr=clion.

Fix: Sort fixers

---

tests/unit/FileReader/ReaderFactoryTest.php

Fix: Reduce visibility of setUp()

---

.php_cs
tests/unit/ApplicationConfigTest.php
tests/unit/ContainerAdapterFactoryTest.php
tests/unit/FileReader/JSONFileReaderTest.php
tests/unit/FileReader/PHPFileReaderTest.php
tests/unit/FileReader/ReaderFactoryTest.php

This PR
💁 For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/1.12#usage:
> **ordered_use [contrib]**
> Ordering use statements.

Enhancement: Enable ordered_use fixer

---

CHANGELOG.md
README.md
composer.json
src/Configurator.php
src/Exception/InvalidConfigException.php
src/Exception/MissingDependencyException.php
src/FileReader/YAMLFileReader.php
tests/unit/Exception/InvalidConfigExceptionTest.php
tests/unit/Exception/MissingDependencyExceptionTest.php
tests/unit/FileReader/ReaderFactoryTest.php
tests/unit/FileReader/YAMLFileReaderTest.php

Enhancement: Implement and register YAMLFileReader

---

CHANGELOG.md
src/Pimple/PimpleContainerAdapter.php
tests/acceptance/SupportsServiceConfig.php

There was a bug which would cause Pimple to fail to create
a service if it's argument was an array or object.

Allow non-string arguments to be used with Pimple

---

CHANGELOG.md
README.md
src/Exception/InvalidConfigException.php
src/League/ServiceServiceProvider.php
src/Pimple/PimpleContainerAdapter.php
src/ServiceDefinition.php
tests/acceptance/SupportsServiceConfig.php
tests/unit/Exception/InvalidConfigExceptionTest.php
tests/unit/ServiceDefinitionTest.php

Allow creating an aliased to another service by name.
At this point, I think it would be better to have separate `ClassServiceDefinition`, `AliasServiceDefinition` and `FactoryServiceDefinition` classes. However, this PR does not do this - it just adds the functionality as I need it now.

Feature: Service Aliases

---

tests/acceptance/AbstractContainerAdapterTest.php
tests/acceptance/LeagueContainerAdapterTest.php
tests/acceptance/PimpleContainerAdapterTest.php

This PR
💁 This makes the most sense as otherwise we hear complains in `AbstractContainerAdapterTest` that the field `$container` is undefined.

Fix: Pull field into AbstractContainerAdapterTest

---

src/ContainerAdapterFactory.php

This PR
💁 The factory actually returns an implementation of `ContainerAdapter`!

Fix: Update return type in docblock

---

src/ContainerAdapterFactory.php
src/Exception/NotContainerAdapterException.php
tests/mocks/NotContainerAdapter.php
tests/unit/ContainerAdapterFactoryTest.php
tests/unit/Exception/NotContainerAdapterExceptionTest.php

Fix: Throw NotContainerAdapterException if adapter is not a ContainerAdapter

---

src/ContainerAdapterFactory.php

Fix: Use instanceof instead of is_a()

---

src/ApplicationConfig.php
src/Configurator.php
src/FileReader/ReaderFactory.php
src/Pimple/PimpleContainerAdapter.php

Fix: Add missing annotations to docblocks

---

tests/mocks/FileReader/CustomFileReader.php

This PR
Follows https://github.com/tomphp/container-configurator/pull/76.
💁‍♂️ It hasn't been an issue so far as we only use the `CustomFileReader` mock once in tests.

Fix: Actually reset static property

---

composer.json

Fix: Require squizlabs/php_codesniffer using concrete version requirement
